// @vitest-environment jsdom
import { expect, it, vi } from 'vitest'
import { readFileSync, existsSync } from 'node:fs'

it('runs the PCB pulse on the login page with shared sizing, theme and hidden-page pause', async () => {
  document.body.innerHTML = readFileSync('login.html', 'utf8')
  const style = document.createElement('style')
  style.textContent = readFileSync('src/smarttest-theme.css', 'utf8') + readFileSync('src/login-motion.css', 'utf8')
  document.head.append(style)
  await import('../src/login-main.js')
  const surface = document.querySelector('[data-login-board]')
  const artwork = surface.querySelector('.pcb-motion')
  expect(surface.dataset.motion).toBe('vivid')
  expect(artwork.getAttribute('viewBox')).toBe('0 0 1120 942')
  expect(getComputedStyle(artwork).width).toBe('min(100vw, 1120px, 118.89svh)')
  const light = artwork.querySelector('.pcb-light')
  const dark = artwork.querySelector('.pcb-dark')
  expect(existsSync(`public${light.getAttribute('href')}`)).toBe(true)
  expect(existsSync(`public${dark.getAttribute('href')}`)).toBe(true)
  expect(getComputedStyle(dark).display).toBe('none')
  const lightRoutes = [...artwork.querySelectorAll('.trace-motion path')].map(path => path.getAttribute('d'))
  document.documentElement.classList.add('dark-theme')
  window.dispatchEvent(new CustomEvent('theme:changed', { detail: { theme: 'dark' } }))
  expect(getComputedStyle(light).display).toBe('none')
  expect(getComputedStyle(dark).display).toBe('block')
  const darkRoutes = [...artwork.querySelectorAll('.trace-motion path')].map(path => path.getAttribute('d'))
  expect(darkRoutes.filter((route, index) => route !== lightRoutes[index])).toHaveLength(2)
  document.documentElement.classList.remove('dark-theme')
  window.dispatchEvent(new CustomEvent('theme:changed', { detail: { theme: 'light' } }))
  expect([...artwork.querySelectorAll('.trace-motion path')].map(path => path.getAttribute('d'))).toEqual(lightRoutes)
  const hidden = vi.spyOn(document, 'hidden', 'get')
  hidden.mockReturnValue(true)
  document.dispatchEvent(new Event('visibilitychange'))
  expect(getComputedStyle(artwork.querySelector('.trace-motion path')).animationPlayState).toBe('paused')
  hidden.mockReturnValue(false)
  document.dispatchEvent(new Event('visibilitychange'))
  expect(surface.classList.contains('motion-hidden')).toBe(false)
  hidden.mockRestore()
  expect(document.querySelector('[data-login-form]')).not.toBeNull()
  style.remove()
})
